name: Build FFmpeg Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64] 
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autopoint \
            libglib2.0-dev \
            jq \
            cmake \
            ninja-build \
            make \
            autoconf \
            automake \
            libtool \
            pkg-config \
            texinfo \
            gettext \
            gperf \
            bison \
            flex \
            git \
            xz-utils \
            unzip \
            diffutils \
            file \
            findutils \
            coreutils \
            binutils \
            python3 \
            python3-pip \
            python3-venv \
            pipx \
            subversion \
            libtool-bin \
            nasm \
            yasm \
            mingw-w64

      - name: Set build environment
        run: |
          echo "ARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "BUILD_TARGET=windows" >> $GITHUB_ENV

      - name: Run build.sh
        run: |
          bash ${{ github.workspace }}/build.sh
        env:
          LATEST_GIT: 1

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.arch }}
          path: ${{ github.workspace }}/out/*.exe
